# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M4hBIL6sDwWEv8o5BATnpc_-SCpZ8hPi
"""

from bs4 import BeautifulSoup as bs
import requests #to access website
import pandas as pd

r = requests.get("https://www.senate.gov/legislative/LIS/roll_call_votes/vote1171/vote_117_1_00290.htm")

soup = bs(r.content)

contents = soup.prettify()

print(contents)

#creating empty list

Name = []
Party = []
Home_State = []
Vote_position = []

websname = soup.find(class_= "newspaperDisplay_3column")
webscontent = websname.find_all(class_="contenttext")

for row in webscontent:
  n = row.text
  Name.append(n)
Name

Master_data = Name[0].split()
Master_data

for i in Master_data:
  if i == "Not":
    i = i.replace("Not","Not_Voting")
  elif i == "Voting":
    Master_data.remove(i)
Master_data

Master_data.index("Cortez")

Master_data[60] = "Cortez-Masto"
Master_data.remove("Masto")

Name = []
for i in range(0,len(Master_data)):
  if i%3 == 0:
    Name.append(Master_data[i])
Name
len(Name)

Vote_position = []
for i in range(2, len(Master_data),3):
  Vote_position.append(Master_data[i])
Vote_position
len(Vote_position)

Party = []
for i in range(1,len(Master_data),3):
  Party.append(Master_data[i][1])
Party

Home_State = []
for i in range(1,len(Master_data),3):
  Home_State.append((Master_data[i][3])+(Master_data[i][4]))
Home_State

Voting_df = pd.DataFrame({"Name": Name,"Party": Party,"Vote Position": Vote_position, "Home State": Home_State})
Voting_df.head(100)

PartyFull = {"D": "Democrat", "R": "Republican"}

Voting_df['Party'] = Voting_df["Party"].map(PartyFull)

Voting_df.head(10)

